default: &default
  adapter: postgresql
  encoding: unicode
  database: job-alert_development
  host: localhost
  pool: 5
  username: nat
  password: password
  
development:
  <<: *default
  database: job-alert_development

test:
  <<: *default
  database: job-alert_test

production:
  <<: *default
  database: job-alert_production
  username: job-alert
  password: <%= ENV['password'] %>


